# -*- coding: utf-8 -*-
"""test_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJ3okZqbfu4xuIDqVl5DLhC4gke3HjlQ
"""
import os
import pickle
import json
import numpy
import joblib
import scipy
import logging
from sklearn.linear_model import Ridge
from azureml.core.model import Model

def init():
  global model 
  model_path =os.path.join(os.getenv("AZUREML_MODEL_DIR"), "model_pkl")  
  model = joblib.load(model_path)
  logging.info("Init complete")

def run(raw_data):
  try:
    logging.info("model 1: request received")
    data = json.loads(raw_data)['data']
    data = numpy.array(data)
    result = model.predict(data)
    logging.info("model 1:request received")
    return result.tolist()
  except Exception as e:
    error =str(e)
    return error